using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Skywalker.SourceGenerators.Tests.Sample;

/// <summary>
/// Trivial sample generator used purely to exercise <see cref="GeneratorTestHelper"/>.
///
/// For each class decorated with <c>[Hello]</c>:
/// - if the class is partial, emit a partial that adds <c>public string Hello() => ...</c>
/// - if the class is not partial, report <c>TEST0001</c>
///
/// The TEST0001 namespace is intentionally separate from the SKY9xxx range so users browsing
/// real diagnostics never see this test fixture.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class HelloGenerator : IIncrementalGenerator
{
    private const string AttributeFullName = "Skywalker.SourceGenerators.Tests.Sample.HelloAttribute";

    private static readonly DiagnosticDescriptor MustBePartial = new(
        id: "TEST0001",
        title: "[Hello] target must be partial",
        messageFormat: "Class '{0}' marked with [Hello] must be declared as partial",
        category: "Skywalker.SourceGenerators.Tests",
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var targets = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                fullyQualifiedMetadataName: AttributeFullName,
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) => Transform(ctx))
            .Where(static x => x is not null);

        context.RegisterSourceOutput(targets, static (spc, target) =>
        {
            if (target is null) return;

            if (!target.IsPartial)
            {
                spc.ReportDiagnostic(Diagnostic.Create(
                    MustBePartial,
                    Location.None,
                    target.ClassName));
                return;
            }

            var ns = string.IsNullOrEmpty(target.Namespace) ? string.Empty : $"namespace {target.Namespace};\n\n";

            var source = $$"""
                // <auto-generated/>
                #nullable enable
                {{ns}}partial class {{target.ClassName}}
                {
                    public string Hello() => "Hello, {{target.ClassName}}!";
                }
                """;

            spc.AddSource($"{target.ClassName}.Hello.g.cs", source);
        });
    }

    private static HelloTarget? Transform(GeneratorAttributeSyntaxContext ctx)
    {
        if (ctx.TargetSymbol is not INamedTypeSymbol type) return null;

        var ns = type.ContainingNamespace.IsGlobalNamespace
            ? string.Empty
            : type.ContainingNamespace.ToDisplayString();

        var isPartial = false;
        foreach (var declaration in type.DeclaringSyntaxReferences)
        {
            if (declaration.GetSyntax() is ClassDeclarationSyntax cls
                && cls.Modifiers.Any(m => m.IsKind(Microsoft.CodeAnalysis.CSharp.SyntaxKind.PartialKeyword)))
            {
                isPartial = true;
                break;
            }
        }

        return new HelloTarget(ns, type.Name, isPartial);
    }

    private sealed record HelloTarget(string Namespace, string ClassName, bool IsPartial);
}
