using Microsoft.CodeAnalysis;

namespace Skywalker.SourceGenerators.Tests.Infrastructure;

internal sealed class HelloWorldIncrementalGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static postInitializationContext =>
        {
            postInitializationContext.AddSource("HelloWorld.g.cs", """
                // <auto-generated/>
                #nullable enable
                namespace Skywalker.Generated;

                internal static class HelloWorld
                {
                    public const string Message = "Hello from source generators.";
                }
                """);
        });
    }
}