using System;
using System.Collections.Immutable;
using System.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Skywalker.Ddd.Abstractions.SourceGenerators;

[Generator(LanguageNames.CSharp)]
public sealed class DependencyInjectionRegistrationGenerator : IIncrementalGenerator
{
    internal const string Category = "Skywalker.Ddd.Abstractions.SourceGenerators";

    internal static readonly DiagnosticDescriptor ServiceTypeMustBeAssignable = new(
        id: "SKY1002",
        title: "Service type must be assignable from implementation type",
        messageFormat: "Service type '{0}' must be assignable from implementation type '{1}'",
        category: Category,
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true,
        helpLinkUri: "https://github.com/dengxuan/Skywalker/blob/main/docs/diagnostics/SKY1002.md");

    private static readonly ImmutableArray<string> AttributeMetadataNames = ImmutableArray.Create(
        "Skywalker.DependencyInjection.ServiceAttribute",
        "Skywalker.DependencyInjection.ApplicationServiceAttribute",
        "Skywalker.DependencyInjection.RepositoryAttribute",
        "Skywalker.DependencyInjection.EventHandlerAttribute");

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static context =>
        {
            context.AddSource("SkywalkerDependencyInjectionAttributes.g.cs", GenerateAttributes());
        });

        var candidates = AttributeMetadataNames
            .Select(attributeName => context.SyntaxProvider.ForAttributeWithMetadataName(
                fullyQualifiedMetadataName: attributeName,
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (context, _) => CreateModel(context)))
            .ToArray();

        var registrations = candidates[0]
            .Collect()
            .Combine(candidates[1].Collect())
            .Combine(candidates[2].Collect())
            .Combine(candidates[3].Collect())
            .Select(static (source, _) => source.Left.Left.Left
                .AddRange(source.Left.Left.Right)
                .AddRange(source.Left.Right)
                .AddRange(source.Right)
                .Distinct()
                .OrderBy(static model => model.ImplementationTypeName, StringComparer.Ordinal)
                .ToImmutableArray());

        context.RegisterSourceOutput(registrations, static (context, models) =>
        {
            if (models.Length > 0)
            {
                context.AddSource("Skywalker.Generated.DependencyInjectionRegistrar.g.cs", GenerateRegistrar(models));
            }
        });
    }

    private static ServiceRegistrationModel CreateModel(GeneratorAttributeSyntaxContext context)
    {
        var type = (INamedTypeSymbol)context.TargetSymbol;
        return new ServiceRegistrationModel(type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat));
    }

    private static string GenerateAttributes()
    {
        return """
            // <auto-generated/>
            // This file was generated by Skywalker Source Generators.
            // Do not modify this file manually.

            #nullable enable
            #pragma warning disable

            namespace Skywalker.DependencyInjection;

            [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
            internal sealed class ServiceAttribute : global::System.Attribute
            {
                public global::System.Type? ServiceType { get; set; }
            }

            [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
            internal sealed class ApplicationServiceAttribute : global::System.Attribute
            {
                public global::System.Type? ServiceType { get; set; }
            }

            [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
            internal sealed class RepositoryAttribute : global::System.Attribute
            {
                public global::System.Type? ServiceType { get; set; }
            }

            [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
            internal sealed class EventHandlerAttribute : global::System.Attribute
            {
                public global::System.Type? ServiceType { get; set; }
            }
            """;
    }

    private static string GenerateRegistrar(ImmutableArray<ServiceRegistrationModel> models)
    {
        var registrations = string.Join(
            "\n",
            models.Select(static model => $"        // TODO #280: emit descriptor for {model.ImplementationTypeName}"));

        return $$"""
            // <auto-generated/>
            // This file was generated by Skywalker Source Generators.
            // Do not modify this file manually.

            #nullable enable
            #pragma warning disable

            namespace Skywalker.Generated;

            internal static class __SkywalkerDependencyInjectionRegistrar
            {
                internal static void Register(global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)
                {
            {{registrations}}
                }
            }
            """;
    }

    private readonly record struct ServiceRegistrationModel(string ImplementationTypeName);
}