using System;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Skywalker.Template.SourceGenerators;

[Generator(LanguageNames.CSharp)]
public sealed class MarkerAttributeGenerator : IIncrementalGenerator
{
    private const string AttributeMetadataName = "Skywalker.Template.SkywalkerGeneratorMarkerAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static context => context.AddSource(
            "SkywalkerGeneratorMarkerAttribute.g.cs",
            """
            // <auto-generated/>
            // This file was generated by Skywalker Source Generators.
            // Do not modify this file manually.

            #nullable enable
            #pragma warning disable

            namespace Skywalker.Template;

            [System.AttributeUsage(System.AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
            internal sealed class SkywalkerGeneratorMarkerAttribute : System.Attribute
            {
            }
            """));

        var targetTypes = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                AttributeMetadataName,
                static (node, _) => node is ClassDeclarationSyntax,
                static (context, _) => ((INamedTypeSymbol)context.TargetSymbol).ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat))
            .Where(static typeName => typeName is not null);

        context.RegisterSourceOutput(targetTypes, static (context, typeName) => Generate(context, typeName));
    }

    private static void Generate(SourceProductionContext context, string typeName)
    {
        var markerName = typeName
            .Replace("global::", string.Empty)
            .Replace('.', '_')
            .Replace('+', '_');

        context.AddSource($"{markerName}.SkywalkerMarker.g.cs", $$"""
            // <auto-generated/>
            // This file was generated by Skywalker Source Generators.
            // Do not modify this file manually.

            #nullable enable
            #pragma warning disable

            namespace Skywalker.Generated;

            internal static class {{markerName}}SkywalkerMarker
            {
                public const string TargetType = "{{typeName}}";
            }
            """);
    }
}