using System;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Skywalker.SourceGenerators;

namespace Skywalker.Ddd.EntityFrameworkCore.SourceGenerators;

[Generator(LanguageNames.CSharp)]
public sealed class RepositoryRegistrationGenerator : IIncrementalGenerator
{
    private const string DbContextMetadataName = "Skywalker.Ddd.EntityFrameworkCore.SkywalkerDbContext`1";
    private const string DbSetMetadataName = "Microsoft.EntityFrameworkCore.DbSet`1";
    private const string EntityMetadataName = "Skywalker.Ddd.Domain.Entities.IEntity";
    private const string EntityWithKeyMetadataName = "Skywalker.Ddd.Domain.Entities.IEntity`1";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var dbContexts = context.SyntaxProvider
            .CreateSyntaxProvider(
                static (node, _) => node is ClassDeclarationSyntax,
                static (context, _) => CreateModel(context.SemanticModel, (ClassDeclarationSyntax)context.Node))
            .Where(static model => model is not null)
            .Select(static (model, _) => model!.Value);

        context.RegisterSourceOutput(dbContexts, static (context, model) => Generate(context, model));
    }

    private static DbContextRegistrationModel? CreateModel(SemanticModel semanticModel, ClassDeclarationSyntax declaration)
    {
        if (semanticModel.GetDeclaredSymbol(declaration) is not INamedTypeSymbol dbContextSymbol
            || !InheritsFrom(dbContextSymbol, DbContextMetadataName))
        {
            return null;
        }

        var entityBuilder = ImmutableArray.CreateBuilder<EntityRegistrationModel>();
        foreach (var member in dbContextSymbol.GetMembers().OfType<IPropertySymbol>())
        {
            if (member.DeclaredAccessibility != Accessibility.Public || member.IsStatic)
            {
                continue;
            }

            if (member.Type is not INamedTypeSymbol propertyType
                || !HasMetadataName(propertyType.ConstructedFrom, DbSetMetadataName)
                || propertyType.TypeArguments.Length != 1
                || propertyType.TypeArguments[0] is not INamedTypeSymbol entityType
                || !Implements(entityType, EntityMetadataName))
            {
                continue;
            }

            entityBuilder.Add(new EntityRegistrationModel(
                entityType.GetFullyQualifiedName(),
                FindPrimaryKeyType(entityType)?.GetFullyQualifiedName()));
        }

        var entities = entityBuilder.ToImmutable();
        if (entities.Length == 0)
        {
            return null;
        }

        return new DbContextRegistrationModel(
            dbContextSymbol.GetFullyQualifiedName(),
            CreateIdentifier(dbContextSymbol),
            new EquatableArray<EntityRegistrationModel>(entities));
    }

    private static void Generate(SourceProductionContext context, DbContextRegistrationModel model)
    {
        var source = new StringBuilder();
        source.AppendLine("// <auto-generated/>");
        source.AppendLine("// This file was generated by Skywalker Source Generators.");
        source.AppendLine("// Do not modify this file manually.");
        source.AppendLine();
        source.AppendLine("#nullable enable");
        source.AppendLine("#pragma warning disable");
        source.AppendLine();
        source.AppendLine("namespace Microsoft.Extensions.DependencyInjection;");
        source.AppendLine();
        source.Append("internal static class ").Append(model.Identifier).AppendLine("SkywalkerRepositoryRegistrations");
        source.AppendLine("{");
        source.Append("    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddSkywalkerGeneratedRepositoriesFor")
            .Append(model.Identifier)
            .AppendLine("(this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)");
        source.AppendLine("    {");

        foreach (var entity in model.Entities)
        {
            if (entity.PrimaryKeyTypeName is null)
            {
                AppendRepositoryRegistration(source, entity.EntityTypeName, null, $"global::Skywalker.Ddd.Domain.Repositories.Repository<{model.DbContextTypeName}, {entity.EntityTypeName}>");
                AppendDomainServiceRegistration(source, entity.EntityTypeName, null, $"global::Skywalker.Identity.Domain.Repositories.EntityFrameworkCoreDomainService<{entity.EntityTypeName}>");
            }
            else
            {
                AppendRepositoryRegistration(source, entity.EntityTypeName, entity.PrimaryKeyTypeName, $"global::Skywalker.Ddd.Domain.Repositories.Repository<{model.DbContextTypeName}, {entity.EntityTypeName}, {entity.PrimaryKeyTypeName}>");
                AppendDomainServiceRegistration(source, entity.EntityTypeName, entity.PrimaryKeyTypeName, $"global::Skywalker.Identity.Domain.Repositories.EntityFrameworkCoreDomainService<{entity.EntityTypeName}, {entity.PrimaryKeyTypeName}>");
            }
        }

        source.AppendLine("        return services;");
        source.AppendLine("    }");
        source.AppendLine("}");

        context.AddSource($"{model.Identifier}.SkywalkerRepositoryRegistrations.g.cs", source.ToString());
    }

    private static void AppendRepositoryRegistration(StringBuilder source, string entityTypeName, string? primaryKeyTypeName, string implementationTypeName)
    {
        if (primaryKeyTypeName is not null)
        {
            AppendTransient(source, $"global::Skywalker.Ddd.Domain.Repositories.IReadOnlyRepository<{entityTypeName}, {primaryKeyTypeName}>", implementationTypeName);
            AppendTransient(source, $"global::Skywalker.Ddd.Domain.Repositories.IBasicRepository<{entityTypeName}, {primaryKeyTypeName}>", implementationTypeName);
            AppendTransient(source, $"global::Skywalker.Ddd.Domain.Repositories.IRepository<{entityTypeName}, {primaryKeyTypeName}>", implementationTypeName);
        }

        AppendTransient(source, $"global::Skywalker.Ddd.Domain.Repositories.IReadOnlyRepository<{entityTypeName}>", implementationTypeName);
        AppendTransient(source, $"global::Skywalker.Ddd.Domain.Repositories.IBasicRepository<{entityTypeName}>", implementationTypeName);
        AppendTransient(source, $"global::Skywalker.Ddd.Domain.Repositories.IRepository<{entityTypeName}>", implementationTypeName);
    }

    private static void AppendDomainServiceRegistration(StringBuilder source, string entityTypeName, string? primaryKeyTypeName, string implementationTypeName)
    {
        if (primaryKeyTypeName is not null)
        {
            AppendTransient(source, $"global::Skywalker.Ddd.Domain.Services.IDomainService<{entityTypeName}, {primaryKeyTypeName}>", implementationTypeName);
        }

        AppendTransient(source, $"global::Skywalker.Ddd.Domain.Services.IDomainService<{entityTypeName}>", implementationTypeName);
    }

    private static void AppendTransient(StringBuilder source, string serviceTypeName, string implementationTypeName)
    {
        source.AppendLine("        global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAdd(");
        source.AppendLine("            services,");
        source.Append("            global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor.Transient(typeof(")
            .Append(serviceTypeName)
            .Append("), typeof(")
            .Append(implementationTypeName)
            .AppendLine(")));");
    }

    private static ITypeSymbol? FindPrimaryKeyType(INamedTypeSymbol entityType)
    {
        foreach (var interfaceType in entityType.AllInterfaces)
        {
            if (HasMetadataName(interfaceType.ConstructedFrom, EntityWithKeyMetadataName)
                && interfaceType.TypeArguments.Length == 1)
            {
                return interfaceType.TypeArguments[0];
            }
        }

        return null;
    }

    private static bool Implements(INamedTypeSymbol type, string metadataName)
        => type.AllInterfaces.Any(interfaceType => HasMetadataName(interfaceType.ConstructedFrom, metadataName));

    private static bool InheritsFrom(INamedTypeSymbol type, string metadataName)
    {
        for (var current = type.BaseType; current is not null; current = current.BaseType)
        {
            if (HasMetadataName(current.ConstructedFrom, metadataName))
            {
                return true;
            }
        }

        return false;
    }

    private static string CreateIdentifier(INamedTypeSymbol symbol)
        => symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)
            .Replace("global::", string.Empty)
            .Replace('.', '_')
            .Replace('+', '_')
            .Replace('<', '_')
            .Replace('>', '_')
            .Replace(',', '_')
            .Replace(' ', '_');

    private static bool HasMetadataName(INamedTypeSymbol symbol, string metadataName)
    {
        var lastDotIndex = metadataName.LastIndexOf('.');
        var expectedNamespace = lastDotIndex < 0 ? string.Empty : metadataName.Substring(0, lastDotIndex);
        var expectedMetadataName = lastDotIndex < 0 ? metadataName : metadataName.Substring(lastDotIndex + 1);
        return symbol.MetadataName == expectedMetadataName
            && symbol.ContainingNamespace.ToDisplayString() == expectedNamespace;
    }
}

internal readonly struct DbContextRegistrationModel : IEquatable<DbContextRegistrationModel>
{
    public DbContextRegistrationModel(string dbContextTypeName, string identifier, EquatableArray<EntityRegistrationModel> entities)
    {
        DbContextTypeName = dbContextTypeName;
        Identifier = identifier;
        Entities = entities;
    }

    public string DbContextTypeName { get; }

    public string Identifier { get; }

    public EquatableArray<EntityRegistrationModel> Entities { get; }

    public bool Equals(DbContextRegistrationModel other)
        => DbContextTypeName == other.DbContextTypeName
            && Identifier == other.Identifier
            && Entities.Equals(other.Entities);

    public override bool Equals(object? obj) => obj is DbContextRegistrationModel other && Equals(other);

    public override int GetHashCode()
    {
        unchecked
        {
            var hash = 17;
            hash = (hash * 31) + DbContextTypeName.GetHashCode();
            hash = (hash * 31) + Identifier.GetHashCode();
            hash = (hash * 31) + Entities.GetHashCode();
            return hash;
        }
    }
}

internal readonly struct EntityRegistrationModel : IEquatable<EntityRegistrationModel>
{
    public EntityRegistrationModel(string entityTypeName, string? primaryKeyTypeName)
    {
        EntityTypeName = entityTypeName;
        PrimaryKeyTypeName = primaryKeyTypeName;
    }

    public string EntityTypeName { get; }

    public string? PrimaryKeyTypeName { get; }

    public bool Equals(EntityRegistrationModel other)
        => EntityTypeName == other.EntityTypeName
            && PrimaryKeyTypeName == other.PrimaryKeyTypeName;

    public override bool Equals(object? obj) => obj is EntityRegistrationModel other && Equals(other);

    public override int GetHashCode()
    {
        unchecked
        {
            var hash = 17;
            hash = (hash * 31) + EntityTypeName.GetHashCode();
            hash = (hash * 31) + (PrimaryKeyTypeName?.GetHashCode() ?? 0);
            return hash;
        }
    }
}