using System.IO;
using System.Runtime.CompilerServices;
using VerifyTests;

namespace Skywalker.SourceGenerators.Tests;

/// <summary>
/// Global Verify configuration applied via <see cref="ModuleInitializerAttribute"/>.
/// Snapshots live next to the test source files in a <c>Snapshots/</c> folder so reviewers
/// can read both halves of the assertion at the same time.
/// </summary>
public static class VerifySettings
{
    [ModuleInitializer]
    public static void Initialize()
    {
        // Teach Verify how to serialize generator trees / diagnostics.
        VerifySourceGenerators.Initialize();

        // Snapshots co-locate with the test class file: <test-file-dir>/Snapshots/<TestClass>.<TestMethod>.verified.cs
        DerivePathInfo((sourceFile, _, type, method) => new PathInfo(
            directory: Path.Combine(Path.GetDirectoryName(sourceFile)!, "Snapshots"),
            typeName: type.Name,
            methodName: method.Name));

        // Strip the auto-generated header (which embeds Roslyn-specific trivia)
        // so snapshots survive Roslyn point-version bumps.
        VerifierSettings.AddScrubber(text =>
            text.Replace("// <auto-generated/>\r\n", string.Empty)
                .Replace("// <auto-generated/>\n", string.Empty));
    }
}
