//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;



/// <summary>
///   A strongly-typed resource class, for looking up localized strings, etc.
/// </summary>
// This class was auto-generated by the StronglyTypedResourceBuilder
// class via a tool like ResGen or Visual Studio.
// To add or remove a member, edit your .ResX file then rerun ResGen
// with the /str option, or rebuild your VS project.
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
internal class Resx {
    
    private static global::System.Resources.ResourceManager resourceMan;
    
    private static global::System.Globalization.CultureInfo resourceCulture;
    
    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    internal Resx() {
    }
    
    /// <summary>
    ///   Returns the cached ResourceManager instance used by this class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Resources.ResourceManager ResourceManager {
        get {
            if (object.ReferenceEquals(resourceMan, null)) {
                global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resx", typeof(Resx).Assembly);
                resourceMan = temp;
            }
            return resourceMan;
        }
    }
    
    /// <summary>
    ///   Overrides the current thread's CurrentUICulture property for all
    ///   resource lookups using this strongly typed resource class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Globalization.CultureInfo Culture {
        get {
            return resourceCulture;
        }
        set {
            resourceCulture = value;
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to https://github.com/dotnetcore/WebApiClient.
    /// </summary>
    internal static string helpLinkUri {
        get {
            return ResourceManager.GetString("helpLinkUri", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to 不支持特性的此构造函数，请使用其它构造函数.
    /// </summary>
    internal static string WA1001_message {
        get {
            return ResourceManager.GetString("WA1001_message", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to 不匹配的特性构造函数.
    /// </summary>
    internal static string WA1001_title {
        get {
            return ResourceManager.GetString("WA1001_title", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to 返回类型必须为ITask&lt;&gt;、Task&lt;&gt;或Task.
    /// </summary>
    internal static string WA1002_message {
        get {
            return ResourceManager.GetString("WA1002_message", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to 不支持的返回类型.
    /// </summary>
    internal static string WA1002_title {
        get {
            return ResourceManager.GetString("WA1002_title", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to 参数不支持ref/out等修饰.
    /// </summary>
    internal static string WA1003_message {
        get {
            return ResourceManager.GetString("WA1003_message", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to 不支持的ref/out修饰.
    /// </summary>
    internal static string WA1003_title {
        get {
            return ResourceManager.GetString("WA1003_title", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to 不支持的非方法声明，只允许方法的声明.
    /// </summary>
    internal static string WA1004_message {
        get {
            return ResourceManager.GetString("WA1004_message", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to 不支持的非方法声明.
    /// </summary>
    internal static string WA1004_title {
        get {
            return ResourceManager.GetString("WA1004_title", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to 不支持声明泛型方法.
    /// </summary>
    internal static string WA1005_message {
        get {
            return ResourceManager.GetString("WA1005_message", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to 不支持的泛型方法.
    /// </summary>
    internal static string WA1005_title {
        get {
            return ResourceManager.GetString("WA1005_title", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to UriAttribute只能修饰于第一个参数.
    /// </summary>
    internal static string WA1006_message {
        get {
            return ResourceManager.GetString("WA1006_message", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to 不支持的修饰的参数索引.
    /// </summary>
    internal static string WA1006_title {
        get {
            return ResourceManager.GetString("WA1006_title", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to 接口必须为public修饰.
    /// </summary>
    internal static string WA1007_message {
        get {
            return ResourceManager.GetString("WA1007_message", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to 不支持的修饰符.
    /// </summary>
    internal static string WA1007_title {
        get {
            return ResourceManager.GetString("WA1007_title", resourceCulture);
        }
    }
}
